### PR TITLE
support building with mingw

### PR DESCRIPTION
**Pull request by totaam**
As per:
https://github.com/mongodb-labs/winkerberos/issues/21

(sorry there are 4 commits - the github webui is not letting me squash them)

### CODE REVIEW

**Comment by behackett** [comment]
Are MINGW_CHOST and MINGW_PREFIX set automatically when mingw-w64 is installed, or do users have to configure them before trying to build?

**Comment by behackett** [comment]
Hi,
I intended to test this patch out today, but I've run into a host of issues. First, I can't get the build working with Python 2.6 or 2.7 using mingw-w64:

```
PS C:\10gen\winkerberos> C:\Python27\python.exe setup.py build -c mingw32
running build
running build_ext
building 'winkerberos' extension
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe -mno-cygwin -mdll -O -Wall -IC:\Python2
7\include -IC:\Python27\PC -c src/winkerberos.c -o build\temp.win-amd64-2.7\Release\src\winkerberos.o
gcc: error: unrecognized command line option '-mno-cygwin'; did you mean '-mno-clwb'?
error: command 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe' failed with exit
 status 1
```

This problem was supposedly fixed in https://bugs.python.org/issue12641, but I'm using a much newer version of Python 2.7, so...

For Python 3.4 I was able to get things to build, but it seems mingw-w64 doesn't play well with the versions of MSVC required for Python 3.5+:

```
PS C:\10gen\winkerberos> C:\Python36\python.exe setup.py build -c mingw32
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    cmdclass={"doc": doc}
  File "C:\Python36\lib\site-packages\setuptools\__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python36\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python36\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Python36\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "C:\Python36\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Python36\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Python36\lib\distutils\cygwinccompiler.py", line 157, in __init__
    self.dll_libraries = get_msvcr()
  File "C:\Python36\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900
```

This problem is discussed with no great solution in https://bugs.python.org/issue25251.

What version of MingW are you using, the original or -w64 (or something else)? And what options are you using to build?

**Comment by totaam** [comment]
Try with [https://www.msys2.org/](MSYS2) instead.
Much easier to install, and all packages will be up to date. (ie: you get Python 3.7, not 3.4)
And tere is no need to set `MINGW_CHOST` by hand or anything else.

**Comment by behackett** [comment]
Thanks for clarifying. I was trying to use the PSF provided Python Windows builds with mingw-w64. I'll try the msys Python builds instead.

**Comment by behackett** [comment]
I got msys2 set up with Python2, 3, and the necessary packages and build tools. After applying your patch the builds succeed. Give me some time to test this all out and I'll get it merged in. I'm out of the office next week, but I should have it sorted out the week after.

Thanks again.

**Comment by behackett** [comment]
Merged to master. Thanks for your patience.

**Pull request closed without merging**
